baseURL = 'https://tyoverby.com/'
languageCode = 'en-us'
title = 'Ty Overby'

[taxonomies]
  tag = 'tags'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Allow HTML in markdown
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1

[permalinks]
  posts = '/posts/:filename/'
  thoughts = '/thoughts/:filename/'
  pages = '/:filename/'
